# Site settings
title: Stephanie Mason Design
email: stephanie@unpetitsquab.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures in knitting, programming, and design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://unpetitsquab.github.io" # the base hostname & protocol for your site
twitter_username: unpetitsquab
github_username:  unpetitsquab

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num"
exclude: [_extras]
